### ISSUE TITLE
Empty feeds with FreshRSS

### ISSUE THREAD

**Issue by fazilaltinel** [newsboat/newsboat#1912]
**Newsboat version (copy the output of `newsboat -v`)**:
```
Newsboat r2.25 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2021 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2021 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `/snap/newsboat/5289/usr/local/bin/newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat r2.25
System: Linux 5.4.0-56-generic (x86_64)
Compiler: g++ 7.5.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3 (compiled with 7.58.0)
SQLite: 3.22.0 (compiled with 3.22.0)
libxml2: compiled with 2.9.4
```

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
urls-source "freshrss"
freshrss-url "https://[DOMAIN.COM]/FreshRSS/p/api/greader.php"
freshrss-login "[USERNAME]"
freshrss-password "[PASSWORD]"
freshrss-show-special-feeds "false"
```

Steps to reproduce the issue:

1. Run `newsboat -d log -l 6`.

2. It loads only RSS feed names. Feeds do not contain any item to read.

**Other info you think is relevant**:

The log after I run `newsboat -d log -l 6`:
```
...
DEBUG: https://[DOMAIN.COM]/FreshRSS/p/api/greader.php/reader/api/0/stream/contents/feed%2F14: added tag [TAG]
INFO: RssParser::fetch_freshrss: f.items.size = 0 
ERROR: FreshRssApi::fetch_feed: Empty response:
...
```

Please see the screenshot
![newsboat_issue_ss](https://user-images.githubusercontent.com/3510852/147329537-2965bd35-0b66-40cd-9ab8-19f70cb2e34b.png)

I use NetNewsWire iOS app to get my feeds from the same self-hosted FreshRSS instance. It works without a problem.

In addition, I get `200` return code when I run:
```
curl -v -I --user [USERNAME] https://[DOMAIN.COM]/FreshRSS/p/api/greader.php
```

I think the problem is that Newsboat tries to fetch feeds from `https://[DOMAIN.COM]/FreshRSS/p/api/greader.php/reader/api/0/stream/contents/feed%2F14` instead of `https://[DOMAIN.COM]/FreshRSS/p/api/greader.php/reader/api/0/stream/contents/feed/F14`.

Best,
Fazil

**Comment by der-lyse** [comment]
I don't use any of the remote APIs, but I suspect you need to reload the feed(s) first, at least that's the case with RSS and Atom feeds. As indicated in the footer, press <kbd>Shift+R</kbd> to reload all feeds or just <kbd>R</kbd> to only reload the selected feed. This should help I reckon. I could be wrong, though.

You might want to configure [`auto-reload yes`](https://newsboat.org/releases/2.25/docs/newsboat.html#auto-reload) to automatically load the feeds on startup to save you the additional keystrokes. And there's also [`reload-time <minutes>`](https://newsboat.org/releases/2.25/docs/newsboat.html#reload-time) to customize the interval of automatic reloads.

**Comment by fazilaltinel** [comment]
Thanks for the reply.

I already reloaded the feeds. However, log shows the same error.

**Comment by Minoru** [comment]
I couldn't reproduce this with Newsboat f348ca85d9d103f1d8e6f34de23fb98b96f601c5 (current `master`) and FreshRSS Docker images (tags `latest` and `edge`). In all cases, I saw feed URLs like  http://localhost:8001/api/greader.php/reader/api/0/stream/contents/feed%2F1

@fazilaltinel, what FreshRSS version are you running?

@PetraOleum, are you still using Newsboat with FreshRSS? Would you be able to look into this?

**Comment by fazilaltinel** [comment]
@Minoru Just installed Newsboat version `r2.25+git225.f348ca85` via Snap. I am seeing the same error message.

FreshRSS version is `1.18.1` which is the latest version.

**Comment by Minoru** [comment]
Okay, so this is the same setup as I had when I used the "latest" tag in Docker.

I'm scratching my head here, because I just looked at the code and it's identical for "request titles" and "request articles". I don't yet understand how Newsboat can get the list of feeds but fail to fetch their articles.

Do you have access to your webserver's logs? I take it you're hosting your own FreshRSS instance, so you probably do have access. Can you please open Newsboat, press <kbd>R</kbd> to reload all feeds (it won't load anything for you of course, but anyway), close Newsboat, then post the logs for that time period? I'm interested in calls to the API. Perhaps that'll help me

**Comment by fazilaltinel** [comment]
I checked my webserver's logs. It seems Newsboat tries to fetch wrong URL. Please see the logs below.

These are the log entries I got when I open Newsboat.
```
[26/Dec/2021:18:51:32 +0000] "POST /FreshRSS/p/api/greader.php/accounts/ClientLogin HTTP/1.1" 200 5934 "-" "Newsboat/r2.25-225-gf348c (Linux x86_64)"
[26/Dec/2021:18:51:32 +0000] "GET /FreshRSS/p/api/greader.php/reader/api/0/subscription/list?output=json HTTP/1.1" 200 13716 "-" "Newsboat/r2.25-225-gf348c (Linux x86_64)"
```

And these are the entries I got when I reload all feeds. I clipped rest of the logs for the sake of clarity.
```
[26/Dec/2021:18:52:11 +0000] "GET /FreshRSS/p/api/greader.php/reader/api/0/stream/contents/feed%2F27?n=20 HTTP/1.1" 404 6087 "-" "Newsboat/r2.25-225-gf348c (Linux x86_64)"
[26/Dec/2021:18:52:12 +0000] "GET /FreshRSS/p/api/greader.php/reader/api/0/stream/contents/feed%2F5?n=20 HTTP/1.1" 404 6087 "-" "Newsboat/r2.25-225-gf348c (Linux x86_64)"
[26/Dec/2021:18:52:12 +0000] "GET /FreshRSS/p/api/greader.php/reader/api/0/stream/contents/feed%2F7?n=20 HTTP/1.1" 404 6087 "-" "Newsboat/r2.25-225-gf348c (Linux x86_64)"
[26/Dec/2021:18:52:13 +0000] "GET /FreshRSS/p/api/greader.php/reader/api/0/stream/contents/feed%2F6?n=20 HTTP/1.1" 404 6087 "-" "Newsboat/r2.25-225-gf348c (Linux x86_64)"
[26/Dec/2021:18:52:14 +0000] "GET /FreshRSS/p/api/greader.php/reader/api/0/stream/contents/feed%2F15?n=20 HTTP/1.1" 404 6087 "-" "Newsboat/r2.25-225-gf348c (Linux x86_64)"
[26/Dec/2021:18:52:14 +0000] "GET /FreshRSS/p/api/greader.php/reader/api/0/stream/contents/feed%2F16?n=20 HTTP/1.1" 404 6087 "-" "Newsboat/r2.25-225-gf348c (Linux x86_64)"
[26/Dec/2021:18:52:15 +0000] "GET /FreshRSS/p/api/greader.php/reader/api/0/stream/contents/feed%2F33?n=20 HTTP/1.1" 404 6087 "-" "Newsboat/r2.25-225-gf348c (Linux x86_64)"
[26/Dec/2021:18:52:16 +0000] "GET /FreshRSS/p/api/greader.php/reader/api/0/stream/contents/feed%2F21?n=20 HTTP/1.1" 404 6087 "-" "Newsboat/r2.25-225-gf348c (Linux x86_64)"
[26/Dec/2021:18:52:16 +0000] "GET /FreshRSS/p/api/greader.php/reader/api/0/stream/contents/feed%2F4?n=20 HTTP/1.1" 404 6087 "-" "Newsboat/r2.25-225-gf348c (Linux x86_64)"
[26/Dec/2021:18:52:17 +0000] "GET /FreshRSS/p/api/greader.php/reader/api/0/stream/contents/feed%2F23?n=20 HTTP/1.1" 404 6087 "-" "Newsboat/r2.25-225-gf348c (Linux x86_64)"
```

**Comment by fazilaltinel** [comment]
I guess I fixed the issue. The issue is with slashes escaped with `%2F`. My webserver (Apache) did not accept `/` escaped with `%2F` by default. To fix the problem, I added `AllowEncodedSlashes NoDecode` to the Apache config file.

The iOS app (NetNewsWire) I used with my self-hosted FreshRSS does not escape slashes. So, there was no problem with the app.

Reference: https://httpd.apache.org/docs/trunk/mod/core.html#allowencodedslashes

**Comment by Minoru** [comment]
Sorry I'm so slow! I'm glad you figured it out though.

I'm still not sure if this is a misunderstanding on our side, or a peculiarity of FreshRSS API. To me, the "feed/1" part is an identifier, but it appears that FreshRSS wants to treat it as a part of a path. Other similar APIs (FeedHQ, Inoreader) seem to treat it as an identifier (and we do escape it for those APIs).

I'm reopening the issue because I still want to get to the bottom of this.

**Comment by uzsolt** [comment]
Are there any news?

**Comment by qkl133217** [comment]
I too am having FreshRSS (apache/ubuntu) feeds show up as empty.  Unfortunately, [fazilaltinel] solution to add AllowEncodedSlashes NoDecode to my apache config file is not resolving the issue.  Using Newsboat 2.30.1.  Newsboat successfully connects via the api to pull feed names.  When you hit l:open on a feed, you get Error: feed contains no items!.   Apache log shows: [24/Feb/2023:12:39:13 -0600] "GET /p/api/greader.php/reader/api/0/stream/contents/feed%2F4?n=100 HTTP/1.1" 404 490 "-" "Newsboat/2.30.1 (Macintosh; Intel Mac OS X)".   FreshRSS is a new install from git.  Version
1.21.0-dev

**Comment by qkl133217** [comment]
Update:  AllowEncodedSlashes NoDecode does work.  Needs to be added to 000-default.conf under Ubuntu.  Newsboat successfully populates the feeds from FreshRSS

**Comment by joelchrono12** [comment]
> Update: AllowEncodedSlashes NoDecode does work. Needs to be added to 000-default.conf under Ubuntu. Newsboat successfully populates the feeds from FreshRSS

This solution worked for me too, having the same problem. I did it via the DietPi installer script, I guess I should tell them to adapt their scripts? I feel this is something Newsboat should handle alone, since Readrops, the client I use on android, works perfectly fine

**Comment by Ozan8** [comment]
I am sorry, I am not familiar with this. All I know is I can connect to the server with http:port, but cannot do so with https://mydomain". I can provide logs and stuff if needed. I am not sure how to be of help. Thank you for your amazing work and answer!

> I still haven't looked into this, but I glanced at [linuxserver.io's Dockerfile for FreshRSS](https://github.com/linuxserver/docker-freshrss/blob/5e08a0338e236c7e99fb9dc99a176bdcfca813df/Dockerfile) just now and it appears to use Nginx + php-fpm. All previous reports of this problem used Apache instead.
> 
> Does Nginx has something similar to Apache's `AllowEncodedSlashes NoDecode`?
